### ISSUE TITLE
Unable to List after Minting 

### ISSUE THREAD

**Issue by OurMAVEN** [tokenocean/maven#4]
URGENT
I had minted 5 RAW 16H paddles and went to mint them.
2% to MAVEN and 98% to GRÜVN

Paddle did not list. 

I logged out, cleared cache and logged back in and tried again.

Did something change in how we list Royalty recipients? or how I list with multiple recipients?

**Comment by OurMAVEN** [comment]
We are still having issues with listing after minting and I do not believe anyone has been assigned this

**Comment by asoltys** [comment]
Setting a price of 0.00002 gives an error in the console "Minimum asking price is 0.000008"

![image](https://user-images.githubusercontent.com/7641/166573569-da7af77f-5247-4b30-b99a-b051b1f353c6.png)

**Comment by asoltys** [comment]
I think this was happening because the 2% royalty on 0.00002 worked out to 0.0000004 L-BTC which was too small an amount to be included in the transaction. I've added some code to just ignore royalties that are less than 800 satoshis now which is about the smallest amount that Liquid will allow for L-BTC outputs.
